spring:
  application:
    name: team2

  cloud:
    compatibility-verifier:
      enabled: false

  data:
    mongodb:
      uri: ${DB_URI}
      authentication-database: ${DB_AUTH}
      database: ${DB_NAME}
      auto-index-creation: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:placeholder}
            client-secret: ${GOOGLE_CLIENT_SECRET:placeholder}
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  messages:
    basename: validation
    encoding: ISO-8859-1

taf:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRES}
    testAPI_url: ${TEST_API_SERVICE_URL}
    testAPI_port: ${TEST_API_SERVICE_PORT}
    selenium_container_url: ${SELENIUM_URL}
    selenium_container_port: ${SELENIUM_PORT}
    oauth2FrontendRedirectUrl: ${OAUTH2_FRONTEND_REDIRECT_URL:http://localhost:4200}

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  #  prefer-ip-address: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST}:${EUREKA_PORT}/eureka

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    enabled: true
    path:  /swagger-ui.html